# Generated by Django 4.2.17 on 2024-12-13 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souscripteur', models.CharField(blank=True, max_length=100, verbose_name='Souscripteur')),
                ('immatriculation', models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='Immatriculation')),
                ('marque_et_modele', models.CharField(blank=True, max_length=100, verbose_name='Marque et Modèle')),
                ('police', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Police')),
                ('duree_en_mois', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Durée en Mois')),
                ('date_effet', models.DateField(verbose_name='Date Effet')),
                ('date_echeances', models.DateField(verbose_name='Date Échéances')),
                ('categorie', models.CharField(choices=[('Categorie1', 'Categorie1'), ('Categorie2', 'Categorie2'), ('Categorie3', 'Categorie3'), ('Categorie4', 'Categorie4'), ('Categorie5', 'Categorie5'), ('Categorie6', 'Categorie6'), ('Categorie7', 'Categorie7')], max_length=15, verbose_name='Catégorie')),
                ('puissance_fiscale', models.IntegerField(blank=True, default=0, verbose_name='Puissance Fiscale')),
                ('nombre_de_place', models.IntegerField(blank=True, default=0, verbose_name='Nombre de Places')),
                ('nom_du_client', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Nom du Client')),
                ('prenom_du_client', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Prénom du Client')),
                ('adresse', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, db_index=True, max_length=15, verbose_name='Téléphone')),
                ('mail', models.EmailField(blank=True, db_index=True, max_length=100, verbose_name='Email')),
                ('avance', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Avance')),
                ('reste', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Reste')),
                ('payer', models.BooleanField(default=False, verbose_name='Payé')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('apporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bureau', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Numéro Bureau')),
                ('nom_du_bureau', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nom du Bureau')),
                ('gerant', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gérant')),
                ('region', models.CharField(choices=[('Dakar', 'Dakar'), ('Diourbel', 'Diourbel'), ('Fatick', 'Fatick'), ('Kaolack', 'Kaolack'), ('Kaffrine', 'Kaffrine'), ('Kédougou', 'Kédougou'), ('Kolda', 'Kolda'), ('Louga', 'Louga'), ('Matam', 'Matam'), ('Saint-Louis', 'Saint-Louis'), ('Sédhiou', 'Sédhiou'), ('Tambacounda', 'Tambacounda'), ('Thiès', 'Thiès'), ('Ziguinchor', 'Ziguinchor')], max_length=20, verbose_name='Région')),
                ('departement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Département')),
                ('localite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localité')),
                ('telephone_bureau', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Téléphone Bureau')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('total_police_vendu', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Total Police Vendu')),
                ('versement', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Versement')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bureaux',
            },
        ),
        migrations.CreateModel(
            name='Apporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_et_prenom', models.CharField(db_index=True, max_length=100, verbose_name='Nom et Prénom')),
                ('telephone', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Téléphone')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mail')),
                ('versement', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Versement')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apporteurs', to='horusapp.bureau', verbose_name='Bureau')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vehicule',
            constraint=models.UniqueConstraint(fields=('nom_du_client', 'prenom_du_client', 'telephone'), name='unique_vehicle_client'),
        ),
    ]
